# Development Dockerfile with hot reload
FROM golang:1.21-alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/cosmtrek/air@latest

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

CMD ["air", "-c", ".air.toml"]